module.exports = {
  GAME_START: "GAME_START",
  GAME_END: "GAME_END",
  ADJUST_POINTS: "ADJUST_POINTS",
  ADJUST_BALLS_REMAIN: "ADJUST_BALLS_REMAIN",
  GAME_RESET: "GAME_RESET",
  NEW_SCORE: "NEW_SCORE",
  REMOVE_SCORE: "REMOVE_SCORE",
  ALL_SCORES: "ALL_SCORES"
};
